# Generated by Django 5.1.3 on 2024-11-08 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0002_convidados'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentes',
            name='reservado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='noivos.convidados'),
        ),
        migrations.AlterField(
            model_name='convidados',
            name='status',
            field=models.CharField(choices=[('AC', 'Aceito'), ('C', 'Cancelado'), ('P', 'Pendente')], default='AC', max_length=2),
        ),
    ]
